let song = {
    title: "EARTH",
    duration: 100000,
    note: [
        { played: false, noted: false, track: 'D', time: 2 },
        { played: false, noted: false, track: 'J', time: 2060 },
        { played: false, noted: false, track: 'D', time: 4340 },
        { played: false, noted: false, track: 'F', time: 5500 },
        { played: false, noted: false, track: 'K', time: 6590 },
        { played: false, noted: false, track: 'J', time: 7720 },
        { played: false, noted: false, track: 'D', time: 8890 },
        { played: false, noted: false, track: 'K', time: 10000 },
        { played: false, noted: false, track: 'J', time: 11100 },
        { played: false, noted: false, track: 'K', time: 12170 },
        { played: false, noted: false, track: 'F', time: 13290 },
        { played: false, noted: false, track: 'J', time: 14360 },
        { played: false, noted: false, track: 'K', time: 15450 },
        { played: false, noted: false, track: 'J', time: 16530 },
        { played: false, noted: false, track: 'D', time: 17630 },
        { played: false, noted: false, track: 'F', time: 18730 },
        { played: false, noted: false, track: 'J', time: 19910 },
        { played: false, noted: false, track: 'K', time: 21070 },
        { played: false, noted: false, track: 'J', time: 22080 },
        { played: false, noted: false, track: 'F', time: 23320 },
        { played: false, noted: false, track: 'F', time: 23830 },
        { played: false, noted: false, track: 'D', time: 24390 },
        { played: false, noted: false, track: 'K', time: 24880 },
        { played: false, noted: false, track: 'J', time: 25510 },
        { played: false, noted: false, track: 'J', time: 26510 },
        { played: false, noted: false, track: 'K', time: 27560 },
        { played: false, noted: false, track: 'F', time: 28660 },
        { played: false, noted: false, track: 'D', time: 29730 },
        { played: false, noted: false, track: 'K', time: 30940 },
        { played: false, noted: false, track: 'D', time: 32090 },
        { played: false, noted: false, track: 'F', time: 33170 },
        { played: false, noted: false, track: 'J', time: 34370 },
        { played: false, noted: false, track: 'K', time: 35380 },
        { played: false, noted: false, track: 'J', time: 36540 },
        { played: false, noted: false, track: 'J', time: 37630 },
        { played: false, noted: false, track: 'F', time: 38720 },
        { played: false, noted: false, track: 'K', time: 39910 },
        { played: false, noted: false, track: 'D', time: 40650 },
        { played: false, noted: false, track: 'K', time: 41500 },
        { played: false, noted: false, track: 'F', time: 42070 },
        { played: false, noted: false, track: 'F', time: 42560 },
        { played: false, noted: false, track: 'J', time: 43240 },
        { played: false, noted: false, track: 'D', time: 44250 },
        { played: false, noted: false, track: 'K', time: 45370 },
        { played: false, noted: false, track: 'D', time: 46390 },
        { played: false, noted: false, track: 'F', time: 47600 },
        { played: false, noted: false, track: 'J', time: 48670 },
        { played: false, noted: false, track: 'J', time: 49710 },
        { played: false, noted: false, track: 'F', time: 50870 },
        { played: false, noted: false, track: 'K', time: 52190 },
        { played: false, noted: false, track: 'F', time: 53070 },
        { played: false, noted: false, track: 'F', time: 54350 },
        { played: false, noted: false, track: 'J', time: 55260 },
        { played: false, noted: false, track: 'F', time: 56580 },
        { played: false, noted: false, track: 'D', time: 57700 },
        { played: false, noted: false, track: 'D', time: 58840 },
        { played: false, noted: false, track: 'K', time: 59750 },
        { played: false, noted: false, track: 'J', time: 60950 },
        { played: false, noted: false, track: 'D', time: 62120 },
        { played: false, noted: false, track: 'F', time: 63290 },
        { played: false, noted: false, track: 'K', time: 64380 },
        { played: false, noted: false, track: 'J', time: 65470 },
        { played: false, noted: false, track: 'K', time: 66620 },
        { played: false, noted: false, track: 'F', time: 67700 },

        
    ]
}